spring:
    application:
        name: sssharding
    sharding:
        datasources:
            ds0:
                url: jdbc:mysql://localhost:3306/db0?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
                username: root
                password: root
            ds1:
                url: jdbc:mysql://localhost:3306/db1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
                username: root
                password: root
