spring:
    application:
        name: sssharding
    sharding:
        datasources:
            ds0:
                url: jdbc:mysql://localhost:3306/db0?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
                username: root
                password: root
            ds1:
                url: jdbc:mysql://localhost:3306/db1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
                username: root
                password: root
        tables:
            user:
                actualDataNodes: ds0.user0,ds0.user1,ds0.user2,ds1.user0,ds1.user1,ds1.user2
                databaseStrategy:
                    shardingColumn: id
                    algorithmExpression: db${id % 2}
                tableStrategy:
                    shardingColumn: id
                    algorithmExpression: user${id % 3}
